# Name of your server
server-name: "MyServer"
# Description of your server
server-description: "server from hcf ._."
# Color server
server-color: "ยง6"
# Map from server from HCF (Hardcore Factions)
server-map: "1"

# Spawn
border-limit: 1000

# Discord
#webhook-url: ""
#webhook-check: false

# GUI
gui-enabled: true

# Cooldowns
cooldown: 
 EnderPearl: 30
 CombatTag: 20
 GoldenApple: 10
 ArcherTag: 10
 Snowball: 15
 AntiTrapper: 150

# Special Items
special-items:
 BowSpider:
  name: ""
  lores: ""

factions:
 playersMax: 4

commands-cooldown:
 report: 45
 logout: 30
 #f-stuck: 50 
 
#blocked-items: [45:0]
blocked-blocks: [45:0] //Added id and meta from item :)
